name: shell commands

on: pull_request

jobs:
    run-shell-command:

        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v3
            - name: echo string
            - name: Multiline script
              run: |
                node -v
                pwd 
